version: '3.9'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  user-service:
    build: ./user_service
    ports:
      - "8000:8000"
    env_file:
      - .env

  worker:
    build: ./worker
    depends_on:
      - redis
    env_file:
      - .env
